version: '3.8'

services:
  web:
    build:
      context: .  # ใช้ directory ปัจจุบันเป็น context
      dockerfile: Dockerfile  # ใช้ Dockerfile ที่อยู่ใน /Backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
